# name: Trigger TA
# on:
#   pull_request:
#   push:
#     branches:
#       - main
#       - prod
#     tags:
#       - '**'
#
# permissions:
#   contents: read
#
# jobs:
#   build:
#     name: Rust CI
#     uses: worldcoin/orb-rustzone/.github/workflows/ta.yaml@ryanbutler-orbs-1219-ta-signing-in-ci
#     with:
#       target_env: stage
#       source: ${{ github.sha }}
#       cargo_profile: artifact
#     permissions: write-all
